### ISSUE TITLE
Current Directory

### ISSUE THREAD

**Issue by OvalAdmin** [LUMC/pytest-workflow#112]
Hi,

I have tried using your package to test [Cookie Cutter](https://cookiecutter.readthedocs.io/en/1.7.2/) templates. I needed to pass in the current directory to the command for this and found there is no canonical means of doing so. 

Using ``cookiecutter .`` as the command fails since Cookie Cutter does not recognize "." as a current directory. I thought I might use substitutions but ``echo "%CD%"`` binds one to windows and ``echo "${pwd}"`` binds one to *nix systems. 

I would like to suggest that one use Pythons ``format`` string method upon commands for command line substitutions. Something akin to the following would be quite clean since Python code is largely system agnostic.
```
- name: Echo
  command: echo {root}
  arguments : 
    root: Path.cwd() 
```
Since `Path` is not generally accessible the following is probably necessary for execution.
```
- name: Echo
  command: echo {root}
  arguments : 
    root: from pathlib import Path; Path.cwd() 
```

**Comment by rhpvorderman** [comment]
Did you try:

```
- name: Echo root
  command: bash -c 'echo $PWD'
```
?

**Comment by rhpvorderman** [comment]
Sorry I misread your question. Your problem is that Windows and Unix have different options to get the current working directory.

But luckily you have python: `python -c "import os; print(os.getcwd())"` . It should work on all systems. Would that work for you?

**Comment by OvalAdmin** [comment]
Yes, the idea was to make the ``command`` system agnostic by processing the it through Python first. So instead of the windows guy using ``echo %CD%`` and the *nix guy using ``echo ${pwd}`` they could both use something like ``echo {root}`` , with root being passed in as an argument using a Python one liner e.g. ``root=Path.cwd()`` would be passed to ``echo {root}`` resulting in ``echo .``. The use case is a bit subtle though and this was meant as a suggestion more then anything else.

As an aside : My original issue, as is always the case, was my own fault. I had switched branches in my repository and had not noticed that the ``cookiecutter.json`` file was missing. Cookiecutter of course had noticed that it was missing and and decided not to inform me much like a tired parent who watches their child playing with a flame for the umteenth time that opts not to say "Be careful ! its hot !" yet again.

**Comment by rhpvorderman** [comment]
> Yes, the idea was to make the command system agnostic by processing the it through Python first. So instead of the windows guy using echo %CD% and the *nix guy using echo ${pwd} they could both use something like echo {root} , with root being passed in as an argument using a Python one liner e.g. root=Path.cwd() would be passed to echo {root} resulting in echo .. The use case is a bit subtle though and this was meant as a suggestion more then anything else.

While I agree that it would be convenient, this feature is out of scope for pytest-workflow. One problem we had with previous test suites is that they had too much of this sort of functionality. More scope means more bugs (inevitably). Pytest-workflow only offers test facilities. When it comes to running, the command string is all that is available. While this setup is very simple, it is also very powerful. Usually the environment can be tweaked to accomodate different settings. (We use the same commands on cloud and HPC backends). Another upside is that we have had very little production-breaking bugs (if any) in pytest-workflow since its inception. There were a few inconveniences, but these have been smoothed out (as far as we know).  This is what we state in the introduction:

> Writing workflows is hard. Testing if they are correct is even harder. Testing with bash scripts or other code has some flaws. Is this bug in the pipeline or in my test-framework? Pytest-workflow aims to make testing as simple as possible so you can focus on debugging your pipeline.

Especially the 'Is this bug in the pipeline or in my test-framework?' is why new features are not added to pytest-workflow light-heartedly.

Furthermore I feel the feature is not needed. Linux and Mac OS X both use the bash shell, and [it can be installed on windows nowadays](https://www.howtogeek.com/249966/how-to-install-and-use-the-linux-bash-shell-on-windows-10/).

Have you tried:

```YAML
- name: my test
  command: bash -c 'echo my test'
```
? That should work on windows assuming bash is installed.

Did this manage to solve your multiplatform compatibility?
