### ISSUE TITLE
Difficulty using with Nextflow due to the `work` folder.

### ISSUE THREAD

**Issue by jrm5100** [LUMC/pytest-workflow#125]
By default, [Nextflow](https://nextflow.io/) creates a `work` directory in the root folder.  This gets copied by `pytest-workflow` unless it gets cleared out first.  This primarily causes issues because:

1. It results in (sometimes large) files being copied unnecessarily.
2. The `work` folder may sometimes contain broken symlinks, resulting in an error.

Obviously the best solution is to remember to clear it out before running tests, but that's not always convenient.

Looking at the code:

https://github.com/LUMC/pytest-workflow/blob/3482ff1c63e46b02bc18d48f64685f064d5f6820/src/pytest_workflow/plugin.py#L383

Being able to set `ignore_dangling_symlinks` to True (or setting that by default) would solve the second problem.  Better (but more involved) would be using  the `ignore` parameter.  Solving for #78 would also work since this folder is generally included in `.gitignore`.

**Comment by rhpvorderman** [comment]
@jrm5100 Thanks for the bugreport!

Yes I thank adding this git-aware option will solve multiple problems in one go, and it will be doable with just one extra command line flag: `--git-aware` (or something like that). 
Unlike an ignore thing where there needs to be some sort of flag that collects multiple options etc etc. That will make the interface more difficult. Also .gitignore supports pattern matching, so we can surf on that instead of implementing our own pattern matching. 

So adding git-aware copying is the simplest most robust solution. 
Currently I have no time to implement it. (Holiday coming next week). But I will look at it after that.

**Comment by rhpvorderman** [comment]
@jrm5100 Can you try:
- `pip install git+https://github.com/LUMC/pytest-workflow.git@gitaware`
- And running pytest with the `--git-aware` option? 

That should exclude your `.git` folder and anything that is ignored or not checked in by git. It uses `git ls-files` internally. 

This is the branch as of yet. After review it will make it into the pytest-workflow 1.6.0 release.

**Comment by jrm5100** [comment]
I can confirm that this works- the `work` folder was successfully ignored.

**Comment by rhpvorderman** [comment]
Thanks. I am glad it works for you! I also tested it myself on an actual workflow repository and the test cases also seem to be sufficient. Thanks for the additional help with testing.
The feature will probably ship as is in the next release. When that is done I will close the issue.

**Comment by rhpvorderman** [comment]
Pytest-workflow 1.6.0 is now available on PyPI and on conda-forge. Thanks again for reporting!
