### ISSUE TITLE
Avoid capturing stdout and stderr

### ISSUE THREAD

**Issue by pkerpedjiev** [LUMC/pytest-workflow#134]
Hi! I love this package. Is there any possibility that it could avoid capturing command stdout and stderr? It would make it much easier to see if something went wrong with a command when run in CI.

**Comment by rhpvorderman** [comment]
Which CI are you using? Github CI for instance allows running commands in case of failure:

```
      - name: Check logs in case of failure.
        if: ${{ failure() }}
        # Get the last 1000 lines of the cromwell log to catch the error.
        run: bash -c 'tail -n 1000 /tmp/pytest_workflow_*/*/log.out'
```

Since all workflows run in a separate thread it is not really possible to display the stdout and stderr on failure. That is why they are saved to files. 

It does make sense though to make a better exit code message. If the exit code  is not zero it makes to display the stderr and stdout as well in the error that pytest throws. I will make an issue for that.

**Comment by pkerpedjiev** [comment]
Thanks for the quick response!

I’m using GitLab CI. It provides error handling but it’s not ideal for the us scenario for two reasons:

1. The error job will run if any job before it fails, not necessarily just the test one.
2. The error job won’t necessarily run on the same machine or share the same volumes as the test job so the log files may not be accessible.

There may be a way around this and I may not have the details perfectly right, but I just wanted to double check about outputting to stdout.

I like your proposal to check the error code and dump the logs if there’s an error. This would save the step of having to download, unzip and open them locally.

**Comment by rhpvorderman** [comment]
> Thanks for the quick response!

Well, starting your issue with "I love this package" has to count for something right? ;-)

Anyway, this problem you have is universal. The normal flow I have is

1. run pytest workflow
2. There is an error. Because I am developing the workflow and normally there is a mistake somewhere.
3. I scroll up the pytest-workflow log, select the output log
4. Use less, cat or tail to view the log.

Ideally pytest-workflow outputs the last x lines of stdout and stderr so that you can get to the error in step 2. X can easily be made a setting.

One other problem that occurs every time you have an error in pytest-workflow is that you get an enormous wall of text with all the errors. This will drown any error output in the log when we put it there. This is a problem that needs to be addressed as well before a next release. 

I will think about how to best implement these features and consult with my colleagues who also use pytest-workflow. If you have any suggestions, please post them at #135 . It might take some time before I can implement this feature, and when I do I want to make sure it is a very convenient feature, that makes pytest-workflow more pleasant to use.

**Comment by pkerpedjiev** [comment]
Wonderful, thanks so much for looking into this! Outputting the last few lines of the stdout and stderr log files is a reasonable compromise.

**Comment by rhpvorderman** [comment]
Hi @pkerpedjiev in the latest pr (#146) this should be fixed. How does pytest-workflow work for you when you install the latest development version? (`pip install git+https://github.com/lumc/pytest-workflow.git`)

**Comment by pkerpedjiev** [comment]
Hi Ruben, Thanks for the update. Unfortunately I switched jobs and no
longer have the need (opportunity?) to use pytest-workflow so I’ll be hard
pressed to try out the latest version and follow up. I really appreciate
you looking into this. I’m sure it’ll help lots of others.

**Comment by rhpvorderman** [comment]
Thanks for reporting back. Good luck on your new job! I consider the issue solved in this case :wink:.
