### ISSUE TITLE
platform-specific settings

### ISSUE THREAD

**Issue by seanrjohnson** [LUMC/pytest-workflow#142]
When testing workflows on different systems, it can be necessary to change settings to platform specific values. 
I'm trying to use pytest-worfklow to test Nextflow workflows. I develop them on my laptop (which doesn't run a job scheduler), but eventually deploy them on an HPC, which uses a job scheduler. Using command line arguments to Nextflow, I can specify whether or not to use the scheduler.

For example:
```bash
nextflow main.nf -profile standard # don't use the scheduler
nextflow main.nf -profile hpc # use the scheduler
```
It would be nice to be able to have a test that looks something like this:
```yaml
- name: workflow test
  command: nextflow main.nf -profile ${PLATFORM}
  files:
    - path: out/out.txt
```
And be able to call pytest-workflow something like this:
```bash
pytest --var PLATFORM=standard --symlink tests # don't use the scheduler
pytest --var PLATFORM=hpc --symlink tests # use the scheduler
```

I can think of a few workarounds (like making two versions of all my test yml files, or duplicating the tests within a single yaml file and using `tag` attributes, or using makefiles to generate tests for different platforms, or putting programs in shell scripts and defining environment variables, or just using pytest base without pytest-workflow), but none of them seem ideal.

 Is there a recommended way to handle things like this? It seems like it must be a common issue with workflows.

Thanks

**Comment by rhpvorderman** [comment]
Duplicating yaml files or duplicating tests is clearly something that should be avoided as these copies might get out of sync and that may resulted in untested behavior which eventually can lead to bugs. Using makefiles also makes the flow much more complicated. 

The best thing to do in all these cases is to modify the platform, rather than modifying your tests. On our cluster we opted to do the "scripts and environment variables approach".  Which was quite doable to implement. All it required was having a script named `cromwell` which was the `java -jar cromwell.jar` command with settings for the correct configuration.

For nextflow there is yet an easier approach: [use the configuration file](https://nextflow.io/docs/latest/config.html). By default nextflow also uses settings from `$HOME/.nextflow/config`. So simply make sure the correct scheduler is specified there and all your tests will run without having to modify anything else.

**Comment by seanrjohnson** [comment]
I haven't had a chance to get back to this. Just testing on my local computer and then moving my workflows to the HPC without retesting has been reliable enough so far.

I use different configs for different workflows, so I don't think the `$HOME/.nextflow/config` way will work directly for me. But I'm confident that some variation of the scripting/environment variables approach will work.

As far as I'm concerned, this issue can be closed. The workarounds you describe seem reasonable to me.

**Comment by rhpvorderman** [comment]
Thank you for getting back to us. I will close the issue. Templating and workflow engine specific accomodations will make the project much more complicated and therefore more bug-prone.
